use std::collections::BTreeSet;

use crate::error::Result;
use crate::expression::{self, qml_string};
use crate::model::{ComponentProperty, PropertyType, ScriptModel, Sfc, Template};

use super::EmissionContext;
use super::node::NodeEmitter;
use super::usage::{self, TemplateUsage};
use super::writer::Writer;

pub(crate) fn emit(
    sfc: &Sfc,
    template: &Template,
    script: &ScriptModel,
    context: &EmissionContext<'_>,
) -> Result<String> {
    let usage = usage::collect(template, context);
    let mut writer = Writer::new();
    emit_header(&mut writer, context, &usage);
    writer.line("");
    writer.open("Vue2Qml.VueElement");
    writer.line("id: root");
    writer.line("tag: \"__component\"");
    writer.formatted_line(format_args!(
        "componentName: {}",
        qml_string(
            script
                .name
                .as_deref()
                .unwrap_or_else(|| component_name(context))
        )
    ));
    writer.formatted_line(format_args!(
        "sourcePath: {}",
        qml_string(&context.source_path.to_string_lossy())
    ));
    emit_required_properties(&mut writer, &script.properties);
    emit_component_properties(&mut writer, &script.properties);
    emit_context_properties(&mut writer, script, &usage);
    emit_styles(&mut writer, sfc);
    if !script.properties.is_empty() || !usage.identifiers.values.is_empty() {
        writer.line("");
    }
    NodeEmitter::new(&mut writer, context).emit_children(&template.children);
    writer.close();
    Ok(writer.finish())
}

fn emit_header(writer: &mut Writer, context: &EmissionContext<'_>, usage: &TemplateUsage) {
    writer.formatted_line(format_args!(
        "// Generated by vue2qml from {}.",
        context.source_path.display()
    ));
    writer.line("// Changes will be overwritten; edit the Vue source or converter instead.");
    writer.line("import QtQuick");
    writer.formatted_line(format_args!(
        "import {} as Vue2Qml",
        qml_string(&context.runtime_import())
    ));
    let imports = usage
        .custom_tags
        .iter()
        .filter_map(|tag| context.component_import(tag))
        .collect::<BTreeSet<_>>();
    for import in imports {
        writer.formatted_line(format_args!("import {}", qml_string(&import)));
    }
}

fn emit_required_properties(writer: &mut Writer, properties: &[ComponentProperty]) {
    let required = properties
        .iter()
        .filter(|property| property.required)
        .map(|property| qml_string(&property.name))
        .collect::<Vec<_>>()
        .join(", ");
    writer.formatted_line(format_args!("requiredProperties: [{required}]"));
}

fn emit_component_properties(writer: &mut Writer, properties: &[ComponentProperty]) {
    for property in properties {
        let name = expression::qml_property_name(&property.name);
        if inherited_property(&name) {
            if let Some(value) = &property.default_value {
                writer.formatted_line(format_args!("{name}: {}", qml_default(value)));
            }
            continue;
        }
        writer.formatted_line(format_args!(
            "property {} {name}: {}",
            property.property_type.qml_name(),
            property_default(property)
        ));
    }
}

fn emit_context_properties(writer: &mut Writer, script: &ScriptModel, usage: &TemplateUsage) {
    let props = script
        .properties
        .iter()
        .map(|property| expression::qml_property_name(&property.name))
        .collect::<BTreeSet<_>>();
    let declarations = script.declarations.iter().cloned().collect::<BTreeSet<_>>();
    let has_app = props.contains("app");
    for original in &usage.identifiers.values {
        let name = expression::qml_property_name(original);
        if props.contains(&name) || inherited_property(&name) || name == "root" {
            continue;
        }
        let is_call = usage.identifiers.calls.contains(original);
        let from_app = script.spreads_app && has_app && !declarations.contains(original);
        let value = if from_app && is_call {
            format!("Vue2Qml.Runtime.method(root.app, {})", qml_string(original))
        } else if from_app {
            format!("Vue2Qml.Runtime.read(root.app, {})", qml_string(original))
        } else if is_call {
            "function() { return null }".to_owned()
        } else {
            "null".to_owned()
        };
        writer.formatted_line(format_args!("property var {name}: {value}"));
    }
}

fn emit_styles(writer: &mut Writer, sfc: &Sfc) {
    if sfc.styles.is_empty() {
        return;
    }
    let styles = sfc
        .styles
        .iter()
        .map(|style| qml_string(&style.content))
        .collect::<Vec<_>>()
        .join(", ");
    writer.formatted_line(format_args!("styleSheets: [{styles}]"));
}

fn component_name<'context>(context: &'context EmissionContext<'_>) -> &'context str {
    context
        .source_path
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or("Component")
}

fn property_default(property: &ComponentProperty) -> String {
    property
        .default_value
        .as_deref()
        .map(qml_default)
        .unwrap_or_else(|| match property.property_type {
            PropertyType::Bool => "false".to_owned(),
            PropertyType::Int | PropertyType::Real => "0".to_owned(),
            PropertyType::String | PropertyType::Url => "\"\"".to_owned(),
            PropertyType::Var => "null".to_owned(),
        })
}

fn qml_default(source: &str) -> String {
    let normalized = expression::normalize(source.trim());
    if normalized.starts_with('{') && normalized.ends_with('}') {
        format!("({normalized})")
    } else {
        normalized
    }
}

fn inherited_property(name: &str) -> bool {
    matches!(
        name,
        "children"
            | "data"
            | "enabled"
            | "focus"
            | "height"
            | "implicitHeight"
            | "implicitWidth"
            | "opacity"
            | "parent"
            | "rotation"
            | "scale"
            | "state"
            | "states"
            | "transform"
            | "transitions"
            | "visible"
            | "width"
            | "x"
            | "y"
            | "z"
    )
}
