use std::env;
use std::path::PathBuf;
use std::process::ExitCode;

use vue2qml::{Converter, ConverterOptions, Error, ErrorKind, validate_qml_tree};

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("vue2qml: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), Error> {
    let arguments = env::args().skip(1).collect::<Vec<_>>();
    if arguments.is_empty()
        || arguments
            .iter()
            .any(|argument| argument == "--help" || argument == "-h")
    {
        print_help();
        return Ok(());
    }
    if arguments
        .iter()
        .any(|argument| argument == "--version" || argument == "-V")
    {
        println!("vue2qml {}", env!("CARGO_PKG_VERSION"));
        return Ok(());
    }
    let (check_only, positional) = parse_arguments(&arguments)?;
    let (input, output) = match positional.as_slice() {
        [command, input] if command == "check" => {
            (PathBuf::from(input), PathBuf::from(".vue2qml-check"))
        }
        [command, input, output] if command == "convert" => {
            (PathBuf::from(input), PathBuf::from(output))
        }
        [command, input, output] if command == "verify" => {
            (PathBuf::from(input), PathBuf::from(output))
        }
        [input, output] => (PathBuf::from(input), PathBuf::from(output)),
        _ => {
            return Err(Error::new(
                ErrorKind::InvalidArguments,
                "expected `vue2qml <input> <output>` or `vue2qml check <input>`",
            ));
        }
    };
    let is_check = check_only || positional.first().is_some_and(|value| value == "check");
    let converter = Converter::new(ConverterOptions {
        check_only: is_check,
    });
    let report = converter.convert(&input, &output)?;
    let verb = if is_check { "Checked" } else { "Converted" };
    println!(
        "{verb} {} Vue component{} ({} generated bytes).",
        report.converted_files(),
        if report.converted_files() == 1 {
            ""
        } else {
            "s"
        },
        report.output_bytes()
    );
    if !is_check {
        println!("QML output: {}", output.display());
    }
    if positional.first().is_some_and(|value| value == "verify") {
        let validation = validate_qml_tree(&output)?;
        println!(
            "Validated {} QML files{}.",
            validation.files_checked,
            if validation.entrypoint_smoked {
                " and smoke-tested src/App.qml"
            } else {
                ""
            }
        );
    }
    Ok(())
}

fn parse_arguments(arguments: &[String]) -> Result<(bool, Vec<String>), Error> {
    let mut check_only = false;
    let mut positional = Vec::new();
    for argument in arguments {
        match argument.as_str() {
            "--check-only" => check_only = true,
            value if value.starts_with('-') => {
                return Err(Error::new(
                    ErrorKind::InvalidArguments,
                    format!("unknown option {value:?}"),
                ));
            }
            _ => positional.push(argument.clone()),
        }
    }
    Ok((check_only, positional))
}

fn print_help() {
    println!(
        "vue2qml {}\n\n\
         Convert Vue single-file components into QML.\n\n\
         USAGE:\n\
           vue2qml <INPUT> <OUTPUT>\n\
           vue2qml convert <INPUT> <OUTPUT>\n\
           vue2qml verify <INPUT> <OUTPUT>\n\
           vue2qml check <INPUT>\n\n\
         OPTIONS:\n\
           --check-only  Parse and generate in memory without writing files\n\
           -h, --help    Print help\n\
           -V, --version Print version",
        env!("CARGO_PKG_VERSION")
    );
}
